### ISSUE TITLE
reply icon too small

### ISSUE THREAD

**Issue by truffaut** [tobyhs/enhanced_pull_request#2]
my eyesight is bad and it can be hard for me to notice 

(would also be nice to have a hotkey combo :pray:)

**Comment by tobyhs** [comment]
@truffaut 

I can try improving the icon, but I'm not a designer (and my geometry is rusty), so this might take a while.

For the hotkey, how would we determine which reply to activate? (There can be more than one reply icon on the screen at a time for different lines/comments)

**Comment by truffaut** [comment]
oh good point, I guess you aren't actively "highlighting" a comment or anything as-is, as for the icon, I *may* be able to help you if you don't mind

**Comment by tobyhs** [comment]
@truffaut Is the reply icon on ee9aad184593aed9afb91677e402512c99c7d8e8 okay? (I tried to make it as large as I can given a space of 16 x 16 pixels)

**Comment by truffaut** [comment]
yes, much better, thanks!
